[package]
name = "befunge-pm"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
interprocess = "2.2.2"
proc-macro2 = "1.0.93"
quote = "1.0.38"
rand = "0.9.0"
syn = "2.0.98"

[dependencies.befunge-if]
path = "../befunge-if/"
